### ISSUE TITLE
Build error on XUbuntu Linux 14.04

### ISSUE THREAD

**Issue by kduske** [ericwa/tyrutils-ericw#36] opened 2016-04-18 19:29 UTC
kristian@kristian-Parallels-Virtual-Platform:~/Documents/tyrutils-ericw/build$ cmake ..
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/kristian/Documents/tyrutils-ericw/build
	kristian@kristian-Parallels-Virtual-Platform:~/Documents/tyrutils-ericw/build$ cmake --build .
	[  1%] Built target man_bspinfo
	Scanning dependencies of target bspinfo
	[  3%] Building C object bspinfo/CMakeFiles/bspinfo.dir/bspinfo.c.o
	[  5%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/cmdlib.c.o
	[  7%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/bspfile.c.o
	[  8%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/log.c.o
	[ 10%] Building C object bspinfo/CMakeFiles/bspinfo.dir/__/common/threads.c.o
	Linking C executable bspinfo
	CMakeFiles/bspinfo.dir/__/common/threads.c.o: In function `RunThreadsOn':
	threads.c:(.text+0x1d1): undefined reference to `pthread_mutexattr_init'
	threads.c:(.text+0x278): undefined reference to `pthread_attr_setstacksize'
	threads.c:(.text+0x2f7): undefined reference to `pthread_create'
	threads.c:(.text+0x34b): undefined reference to `pthread_join'
	collect2: error: ld returned 1 exit status
	make[2]: *** [bspinfo/bspinfo] Error 1
	make[1]: *** [bspinfo/CMakeFiles/bspinfo.dir/all] Error 2
	make: *** [all] Error 2

Possibly relevant on stackoverflow: http://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux

**Comment by kduske** [comment] 2016-04-18 19:30
Output of the initial makefile generation:

	kristian@kristian-Parallels-Virtual-Platform:~/Documents/tyrutils-ericw/build$ cmake ..
	-- The C compiler identification is GNU 4.8.4
	-- The CXX compiler identification is GNU 4.8.4
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Looking for include file pthread.h
	-- Looking for include file pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - not found
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Found Threads: TRUE  
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/kristian/Documents/tyrutils-ericw/build

**Comment by ericwa** [comment] 2016-04-18 19:40
Thanks.. I can reproduce this, and `make VERBOSE=1` shows it's not passing any pthreads related flags when compiling bspinfo.
Looks like I'm not using `find_package (Threads)` correctly, one sec

**Comment by ericwa** [comment] 2016-04-18 20:04
@kduske The build on Ubuntu should be fixed now, there were a few other errors I had to fix as well

**Closed by ericwa** 2016-04-18 20:04 UTC

**Comment by kduske** [comment] 2016-04-18 20:17
Thanks!
